version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: slo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slo_db
    ports:
      - "5450:5432"

volumes:
  postgres_data:
